"""
Pulls one real example JNB job per city (per forms_in_progress/registry.py) and writes
that city's permit_data.json, so every form for that city fills from real data actually
pulled from JNB instead of cities sharing a job.

Garden Grove is pinned to a known example (registry.FORMS["garden_grove"]["pinned_jnid"])
instead of being queried for the newest job - kept stable since it's the most reviewed
example - but is still fetched live each run, so it reflects any updates made to that job
in JobNimbus rather than going stale as a frozen file would.

Re-run this whenever you want to pick up newer example jobs (e.g. once more jobs have the 4
engineer-entered custom fields populated) - find_example_job() in example_jobs.py always
prefers a job with those fields filled in, with no code changes needed as better examples
appear. Also regenerates PROGRESS.md so the record of what was pulled stays in sync.
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from dotenv import load_dotenv
load_dotenv(Path.home() / ".env")

from registry import FORMS, HERE, data_path
from example_jobs import find_example_job, fetch_contact_for_job, build_example_data
from pipeline import jnb_client
from pipeline.transformer import _job_address


def _pull_city(city_key: str, cfg: dict) -> dict:
    pinned_jnid = cfg.get("pinned_jnid")
    if pinned_jnid:
        job = jnb_client.get_job(pinned_jnid)
        custom_fields_complete, missing_fields = True, []  # confirmed once when originally pinned
    else:
        found = find_example_job(cfg["display_name"])
        if found is None:
            return {
                "city_key": city_key, "city_name": cfg["display_name"], "pinned": False,
                "jnid": None, "job_name": None, "job_address": None,
                "custom_fields_complete": False, "missing_fields": [],
                "data_path": None, "error": "No jobs found for this city in JobNimbus.",
            }
        job = found["job"]
        custom_fields_complete, missing_fields = found["custom_fields_complete"], found["missing_fields"]

    contact = fetch_contact_for_job(job)
    data = build_example_data(job, contact)

    out_path = data_path(city_key)
    out_path.write_text(json.dumps(data, indent=2))

    return {
        "city_key": city_key,
        "city_name": cfg["display_name"],
        "pinned": bool(pinned_jnid),
        "jnid": job.get("jnid"),
        "job_name": job.get("name"),
        "job_address": _job_address(job),
        "custom_fields_complete": custom_fields_complete,
        "missing_fields": missing_fields,
        "data_path": str(out_path.relative_to(HERE.parent)),
    }


def _render_progress_md(reports: list[dict]) -> str:
    lines = [
        "# forms_in_progress — example jobs pulled from JobNimbus",
        "",
        "Auto-generated by `build_data.py` — re-run that script to refresh this file, do not "
        "edit by hand.",
        "",
        "One real JNB job per city feeds every form for that city (see `registry.py`), so "
        "each city's POC reflects its own real data instead of cities sharing a job. The 4 "
        "engineer-entered custom fields (`Job_description`, `Structure`, `Existing_panels`, "
        "`System_kw_ac`) were added to JNB on 2026-05-29, so most jobs won't have them "
        "populated yet — `find_example_job()` in `example_jobs.py` always prefers a job that "
        "does, and falls back to the most recent job in that city otherwise. Re-running this "
        "script will automatically pick up better examples as more jobs get those fields "
        "filled in, with no code changes needed. Pinned cities (see `registry.py`) always use "
        "the same job (fetched fresh each run) instead of the newest match, to stay stable "
        "while under active review.",
        "",
        "| City | JNID | Job | Address | Custom fields populated? | Data file |",
        "|---|---|---|---|---|---|",
    ]
    for r in reports:
        if r.get("error"):
            lines.append(f"| {r['city_name']} | — | — | — | {r['error']} | — |")
            continue
        pinned_note = " (pinned)" if r["pinned"] else ""
        cf = "Yes" if r["custom_fields_complete"] else f"No — missing {', '.join(r['missing_fields'])}"
        lines.append(
            f"| {r['city_name']}{pinned_note} | `{r['jnid']}` | {r['job_name']} | "
            f"{r['job_address']} | {cf} | `{r['data_path']}` |"
        )
    return "\n".join(lines) + "\n"


def main():
    reports = []
    for city_key, cfg in FORMS.items():
        print(f"Pulling example job for {cfg['display_name']}...")
        report = _pull_city(city_key, cfg)
        reports.append(report)
        if report.get("error"):
            print(f"  ERROR: {report['error']}")
        else:
            cf_note = "custom fields populated" if report["custom_fields_complete"] else \
                f"custom fields NOT populated (missing: {', '.join(report['missing_fields'])})"
            pinned_note = " [pinned]" if report["pinned"] else ""
            print(f"  {report['jnid']}  {report['job_name']!r}  ({cf_note}){pinned_note}")

    progress_path = HERE / "PROGRESS.md"
    progress_path.write_text(_render_progress_md(reports))
    print(f"\nWrote {progress_path}")


if __name__ == "__main__":
    main()
