"""
Pulls one real example JNB job per city in forms/ and writes it to output/<city>/permit_data.json,
so every form for that city fills from real data actually pulled from JNB instead of cities
sharing a job.

Cities are discovered from forms/ itself - every subdirectory is a city, no separate list to
keep in sync. Which real JNB city name to search for is the folder's own name (de-normalized,
"fountain_valley" -> "Fountain Valley") unless a mapping in that folder declares a "cities" list
(the LA County / San Diego County case - a job's real city is never literally "LA County", so
each of those declared aliases gets tried in order until one has jobs).

Re-run this whenever you want to pick up newer example jobs (e.g. once more jobs have the 4
engineer-entered custom fields populated) - find_example_job() in example_jobs.py always
prefers a job with those fields filled in, with no code changes needed as better examples
appear. Also regenerates output/PROGRESS.md so the record of what was pulled stays in sync
(lives under output/, not docs/, since it lists real customer names/addresses per city - same
gitignored territory as the permit_data.json files it's describing).
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from dotenv import load_dotenv
load_dotenv(Path.home() / ".env")

from forms.fill import _load
from forms.registry import FORMS_DIR
from forms.example_jobs import find_example_job, fetch_contact_for_job, build_example_data
from pipeline.transformer import _job_address

ROOT = FORMS_DIR.parent
OUTPUT_DIR = ROOT / "output"


def _display_name(city_key: str) -> str:
    return city_key.replace("_", " ").title()


def _jnb_city_candidates(city_dir: Path) -> list[str]:
    """The real JNB city value(s) to search for this folder's example job - a mapping's own
    "cities" alias list if it declares one, else the folder's de-normalized name."""
    for mapping_path in sorted(city_dir.glob("mapping*.json")):
        mapping = _load(mapping_path)
        if mapping.get("cities"):
            return mapping["cities"]
    return [_display_name(city_dir.name)]


def _pull_city(city_dir: Path) -> dict:
    display_name = _display_name(city_dir.name)
    candidates = _jnb_city_candidates(city_dir)

    found = None
    for city in candidates:
        found = find_example_job(city)
        if found is not None:
            break

    if found is None:
        return {
            "city_key": city_dir.name, "city_name": display_name,
            "jnid": None, "job_name": None, "job_address": None,
            "custom_fields_complete": False, "missing_fields": [],
            "data_path": None, "error": "No jobs found for this city in JobNimbus.",
        }

    job = found["job"]
    contact = fetch_contact_for_job(job)
    data = build_example_data(job, contact)

    out_dir = OUTPUT_DIR / city_dir.name
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / "permit_data.json"
    out_path.write_text(json.dumps(data, indent=2))

    return {
        "city_key": city_dir.name,
        "city_name": display_name,
        "jnid": job.get("jnid"),
        "job_name": job.get("name"),
        "job_address": _job_address(job),
        "custom_fields_complete": found["custom_fields_complete"],
        "missing_fields": found["missing_fields"],
        "data_path": str(out_path.relative_to(ROOT)),
    }


def _render_progress_md(reports: list[dict]) -> str:
    lines = [
        "# forms/ — example jobs pulled from JobNimbus",
        "",
        "Auto-generated by `build_data.py` — re-run that script to refresh this file, do not "
        "edit by hand.",
        "",
        "One real JNB job per city feeds every form for that city, so each city's example "
        "reflects its own real data instead of cities sharing a job. The 4 engineer-entered "
        "custom fields (`Job_description`, `Structure`, `Existing_panels`, `System_kw_ac`) "
        "were added to JNB on 2026-05-29, so most jobs won't have them populated yet — "
        "`find_example_job()` in `example_jobs.py` always prefers a job that does, and falls "
        "back to the richest job in that city otherwise. Re-running this script will "
        "automatically pick up better examples as more jobs get those fields filled in, with "
        "no code changes needed.",
        "",
        "| City | JNID | Job | Address | Custom fields populated? | Data file |",
        "|---|---|---|---|---|---|",
    ]
    for r in reports:
        if r.get("error"):
            lines.append(f"| {r['city_name']} | — | — | — | {r['error']} | — |")
            continue
        cf = "Yes" if r["custom_fields_complete"] else f"No — missing {', '.join(r['missing_fields'])}"
        lines.append(
            f"| {r['city_name']} | `{r['jnid']}` | {r['job_name']} | "
            f"{r['job_address']} | {cf} | `{r['data_path']}` |"
        )
    return "\n".join(lines) + "\n"


def main():
    reports = []
    for city_dir in sorted(p for p in FORMS_DIR.iterdir() if p.is_dir()):
        display_name = _display_name(city_dir.name)
        print(f"Pulling example job for {display_name}...")
        report = _pull_city(city_dir)
        reports.append(report)
        if report.get("error"):
            print(f"  ERROR: {report['error']}")
        else:
            cf_note = "custom fields populated" if report["custom_fields_complete"] else \
                f"custom fields NOT populated (missing: {', '.join(report['missing_fields'])})"
            print(f"  {report['jnid']}  {report['job_name']!r}  ({cf_note})")

    progress_path = OUTPUT_DIR / "PROGRESS.md"
    progress_path.write_text(_render_progress_md(reports))
    print(f"\nWrote {progress_path}")


if __name__ == "__main__":
    main()
